export const MONEY_QUOTES = [
  "Wealth consists not in having great possessions, but in having few wants. - Epictetus",
  "But there’s only one way to stay wealthy: some combination of frugality and paranoia. - Morgan Housel",
  "I always try to be smart. I try to treat all the money I'm making like it's the last time I'm going to make it. - Eminem",
  "He is richest who is content with the least, for content is the wealth of nature. - Socrates",
  "Money is a scoreboard where you can rank how you're doing against other people. - Mark Cuban",
  "People have the capability to change their inner relationship and conversation with money. - Loral Langemeier",
  "Only buy something that you’d be perfectly happy to hold if the market shuts down for ten years. - Warren Buffett",
  "Wealth does not make people happy, but positive increases in wealth may. - Nassim Nicholas Taleb",
  "The poor and the middle class work for money. The rich have money work for them. - Robert Kiyosaki",
  "Money is the barometer of a society's virtue. - Ayn Rand",
  "The key to making money is to stay invested. - Suze Orman",
  "I've got all the money I'll ever need, if I die by four o'clock. - Henny Youngman",
  "Too many people spend money they earned..to buy things they don't want..to impress people that they don't like. - Will Rogers",
  "A wise person should have money in their head, but not in their heart. - Jonathan Swift",
  "Buy land. They’re not making it anymore. - Mark Twain",
  "Money often costs too much. - Ralph Waldo Emerson",
  "To fulfill a dream, to be allowed to sweat over lonely labor, to be given a chance to create, is the meat and potatoes of life. The money is the gravy. - Bette Davis",
  "Everyday is a bank account, and time is our currency. No one is rich, no one is poor, we've got 24 hours each. - Christopher Rice",
  "Money is a terrible master but an excellent servant. - P.T. Barnum",
  "Try to save something while your salary is small; it’s impossible to save after you begin to earn more. - Jack Benny",
  "Money is the opposite of the weather. Nobody talks about it, but everybody does something about it. - Rebecca Johnson",
  "Spending money is much more difficult than making money. - Jack Ma",
  "I've made all my money on my own without my family, and I work very hard. - Paris Hilton",
  "The only reason I'm in Hollywood is that I don't have the moral courage to refuse the money. - Marlon Brando",
  "You either master money, or, on some level, money masters you. - Tony Robbins",
  "A person either disciplines his finances or his finances discipline him. - Orrin Woodward",
  "Each of us has a financial genius within us but the problem is our financial genius lies asleep waiting to be called on. - Robert T. Kiyosaki",
  "The easiest way for your children to learn about money is for you not to have any. - Katharine Whitehorn",
  "Capital as such is not evil; it is its wrong use that is evil. Capital in some form or other will always be needed. - Mahatma Gandhi",
  "Wealth is the ability to fully experience life. - Henry David Thoreau",
  "The individual investor should act consistently as an investor and not as a speculator. - Ben Graham",
  "If you are in the world of business, that means you are in the business of making money. - Stephen A. Smith",
  "This is true in personal finance, where you’re told to have a six-month emergency fund and save 10% of your salary. - Morgan Housel",
  "You must gain control over your money or the lack of it will forever control you. - Dave Ramsey",
  "Investing should be more like watching paint dry or watching grass grow. If you want excitement, take $800 and go to Las Vegas. - Paul Samuelson",
  "A nickel ain't worth a dime anymore. - Yogi Berra",
  "The price of anything is the amount of life you exchange for it. - Henry David Thoreau",
  "Most people only talk and dream of getting rich. The most important thing is to do something. You’re only poor if you give up. - Robert Kiyosaki",
  "Every time you borrow money, you're robbing your future self. - Nathan W. Morris",
  "A man in debt is so far a slave. - Ralph Waldo Emerson",
  "Never spend your money before you have it. - Thomas Jefferson",
  "Many people take no care of their money till they come nearly to the end of it, and others do just the same with their time. - Johann Wolfgang von Goethe",
  "The only point in making money is, you can tell some big shot where to go. - Humphrey Bogart",
  "The rich know that money is an illusion. - Robert T. Kiyosaki",
  "Finance is the art of passing money from hand to hand until it finally disappears. - Robert W. Sarnoff",
  "Making money isn’t hard in itself… What’s hard is to earn it by doing something worth devoting one’s life to. - Carlos Ruiz Zafon",
  "Wealth is not his that has it, but his that enjoys it. - Benjamin Franklin",
  "Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver. - Ayn Rand",
  "It is not the man who has too little, but the man who craves more, that is poor. - Seneca",
  "Where large sums of money are concerned, it is advisable to trust nobody. - Agatha Christie",
  "It’s amazing how fast later comes when you buy now. - Milton Berle",
  "The best investment is in the tools of one's own trade. - Benjamin Franklin",
  "It's not how much money you make, but how much money you keep, how hard it works for you, and how many generations you keep it for. - Robert Kiyosaki",
  "It's amazing. The moment you show cash, everyone knows your language. - Aravind Adiga",
  "The secret to wealth is simple: find a way to do more for others than anyone else does. Become more valuable. - Tony Robbins",
  "Wealth is the slave of a wise man. The master of a fool. - Seneca",
  "The trick is to stop thinking of it as 'your' money. - IRS auditor",
  "You use your money to buy privacy because during most of your life you aren't allowed to be normal. - Johnny Depp",
  "There is no price set on the lavish summer, and June may be had by the poorest comer. - James Russell Lowell",
  "Don't tell me what you value, show me your budget, and I'll tell you what you value. - Joe Biden",
  "Money and success don't change people; they merely amplify what is already there. - Will Smith",
  "Before you can become a millionaire, you must learn to think like one. You must learn how to motivate yourself to counter fear with courage. - Thomas J. Stanley",
  "Interest never sleeps nor sickens nor dies. - J. Reuben Clark",
  "Work like you don't need the money. Love like you've never been hurt. Dance like nobody's watching. - Satchel Paige",
  "Money does not buy you happiness, but lack of money certainly buys you misery. - Daniel Kahneman",
  "No, I never thought about my father's money as my money. - Christie Hefner",
  "Have good money habits. Learn to pay yourself first. Paying yourself first makes you financially stronger, mentally, and fiscally. - Robert T. Kiyosaki",
  "Everything has a price, but not all prices appear on labels. - Morgan Housel",
  "Wealth after all is a relative thing since he that has little and wants less is richer than he that has much and wants more. - Charles Caleb Colton",
  "I’m only rich because I know when I’m wrong…I basically have survived by recognizing my mistakes. - George Soros",
  "My old father used to have a saying: If you make a bad bargain, hug it all the tighter. - Abraham Lincoln",
  "Save money and money will save you. - Jamaican Proverb",
  "When you understand that your self-worth is not determined by your net worth, then you’ll have financial freedom. - Suze Orman",
  "How many millionaires do you know who have become wealthy by investing in savings accounts? I rest my case. - Robert G. Allen",
  "The rich know that savings are only used to create more money, not to pay bills. - Robert T. Kiyosaki",
  "It’s easy to say you don’t care about money when you have plenty of it. - Ransom Riggs",
  "Find something in life that you love doing. If you make a lot of money, that's a bonus, and if you don't, you still won't hate going to work. - Jeff Foxworthy",
  "Any fool can spend money. But to earn it and save it and defer gratification – then you learn to value it differently. - Malcolm Gladwell",
  "The best investment you can make is in yourself. - Warren Buffett",
  "Money poisons you when you've got it, and starves you when you haven't. - D.H.Lawrence",
  "I'd like to live as a poor man with lots of money. - Pablo Picasso",
  "If we command our wealth, we shall be rich and free. If our wealth commands us, we are poor indeed. - Edmund Burke",
  "The greatest wealth is to live content with little. - Plato",
  "Money is the most universal and most efficient system of mutual trust ever devised. - Yuval Noah Harari",
  "Debt erases freedom more surely than anything else. - Merryn Somerset Webb",
  "When money realizes that it is in good hands, it wants to stay and multiply in those hands. - Idowu Koyenikan",
  "Making money from money is like aerobatics. - Alisher Usmanov",
  "If you would know the value of money, go and try to borrow some. - Benjamin Franklin",
  "I don't mind that I'm fat. You still get the same money. - Marlon Brando",
  "For most people, the reason they don’t win financially is because the pain of losing money is far greater than the joy of being rich. - Robert T. Kiyosaki",
  "Money is a tool. Used properly it makes something beautiful; used wrong, it makes a mess! - Bradley Vinson",
  "If you want to know what God thinks of money, just look at the people he gave it to. - Dorothy Parker",
  "The more your money works for you, the less you have to work for money. - Idowu Koyenikan",
  "The money you make is a symbol of the value you create. - Idowu Koyenikan",
  "The stock market is a device for transferring money from the impatient to the patient. - Warren Buffett",
  "One of the most powerful ways to increase your savings isn’t to raise your income. It’s to raise your humility. - Morgan Housel",
  "Money is always eager and ready to work for anyone who is ready to employ it. - Idowu Koyenikan",
  "If you can’t make up your mind decisively, then you’ll never learn to make money anyway. - Robert Kiyosaki",
  "People who want to make a million borrow a million first. - Sophie Kinsella",
  "People who advocate simplicity have money in the bank; the money came first, not the simplicity. - Douglas Coupland",
  "Money comes with a price, and for me, the price is both freedom and a real life. - Savi Sharma",
  "Making money is a common sense. It’s not rocket science. But unfortunately, when it comes to money, common sense is uncommon. - Robert Kiyosaki",
  "The worst sin you can ever commit to yourself is to sit and wait for someone to give you money. - Mac Duke The Strategist",
  "Do not aim to be coldly rational when making financial decisions. Aim to just be pretty reasonable. - Morgan Hausel",
  "Assets will put money in your pocket while a liability will take money out of your pocket. - Robert T. Kiyosaki",
  "The lack of money is the root of all evil. - Mark Twain",
  "It's all about the money. - Joe Jackson",
  "Money does not make you happy but it quiets the nerves. - Sean O'Casey",
  "If you would be wealthy, think of saving as well as getting. - Benjamin Franklin",
  "Do not save what is left after spending; instead spend what is left after saving. - Warren Buffett",
  "Just because you can afford it doesn’t mean you should buy it. - Suze Orman",
  "Money can’t buy happiness, but it will certainly get you a better class of memories. - Ronald Reagan",
  "Debt is the slavery of the free. - Publilius Syrus",
  "Saving is a hedge against life’s inevitable ability to surprise the hell out of you at the worst possible moment. - Morgan Hausel",
  "The two most beautiful words in the English language are 'check enclosed.' - Dorothy Parker",
  "The single most powerful asset you have is your mind. If it is trained well, it can create enormous wealth. - Robert T. Kiyosaki",
  "Rule No. 1 is never lose money. Rule No. 2 is never forget Rule No. 1. - Warren Buffett",
  "Money is not the most important thing in the world. Love is. Fortunately, I love money. - Jackie Mason",
  "Compound interest is the eighth wonder of the world. He who understands it, earns it. He who doesn’t, pays it. - Albert Einstein",
  "Getting money is one thing. Keeping it is another. - Morgan Housel",
  "The most important law of money: 'Give, and you shall receive.' - Robert T. Kiyosaki",
  "Do what you love and the money will follow. - Marsha Sinetar",
  "It’s not your salary that makes you rich; it’s your spending habits. - Charles A. Jaffe",
  "Hold material goods and wealth on a flat palm and not in a clenched fist. - Alistair Begg",
  "You'd be surprised what people will do for money that they wouldn't do for Love. - Rachel Caine",
  "Never depend on a single income. Make investments to create a second source. - Warren Buffett",
  "Money is one form of Power. But what is more powerful is Financial Education. - Robert T. Kiyosaki",
  "Remember that the only purpose of money is to get you what you want, so think hard about what you value and put it above money. - Ray Dalio",
  "Never stand begging for that which you have the power to earn. - Miguel de Cervantes",
  "Wars in old times were made to get slaves. The modern implement of imposing slavery is debt. - Ezra Pound",
  "Controlling your time is the highest dividend money pays. - Morgan Housel",
  "Debt gives you the ability to look like you’re winning when you’re not. - Dave Ramsey",
  "The man who never has money enough to pay his debts has too much of something else. - James Lendall Basford",
  "In this world, nothing is certain except death and taxes. - Benjamin Franklin",
  "A savvy investor knows that the seemingly worst of times is actually the best of times to make money. - Robert T. Kiyosaki",
  "Rather go to bed without dinner than to rise in debt. - Benjamin Franklin",
  "If you think nobody cares if you’re alive, try missing a couple of car payments. - Earl Wilson",
  "When you define savings as the gap between your ego and your income you realize why many people with decent incomes save so little. - Morgan Hausel",
  "Early to bed, early to rise, keeps you healthy, wealthy and wise. - Benjamin Franklin",
  "Wealth is in information. The person who has the timeliest information owns the wealth. - Robert T. Kiyosaki",
  "When prosperity comes, do not use all of it. - Confucius",
  "Money isn’t everything, but it’s right up there with oxygen. - Zig Ziglar",
  "A man who pays his bills on time is soon forgotten. - Oscar Wilde",
  "Using your money to buy time and options has a lifestyle benefit few luxury goods can compete with. - Morgan Housel",
  "Money, like emotions, is something you must control to keep your life on the right track. - Natasha Munson",
  "A budget doesn’t limit your freedom; it gives you freedom. - Rachel Cruze",
  "More money will not solve problems. Most people, given more money, only get into more debt. - Robert Kiyosaki",
  "To contract new debts is not the way to pay old ones. - George Washington",
  "My problem lies in reconciling my gross habits with my net income. - Errol Flynn",
  "Nothing wrong with making money. - Adam Levine",
  "You have to find a way that works for you to focus on prosperity despite the bills around you. - Rhonda Byrne",
  "The challenge is not to pick the best investment. The challenge is to pick the right investment. - Don Connelly",
  "Money is like muck—not good unless it be spread. - Francis Bacon",
  "Intelligence solves problems and produces money. Money without financial intelligence is money soon gone. - Robert T. Kiyosaki",
  "If you’re saving, you’re succeeding. - Steve Burkholder",
  "The big money is not in the buying and selling, but in the waiting. - Charlie Munger",
  "Making money is certainly the one addiction I cannot shake. - Felix Dennis",
  "Wealth is just the accumulated leftovers after you spend what you take in. - Morgan Hausel",
  "I made my money the old-fashioned way. I was very nice to a wealthy relative right before he died. - Malcolm Forbes",
  "Know what you own, and know why you own it. - Peter Lynch",
  "A budget is telling your money where to go instead of wondering where it went. - Dave Ramsey",
  "Too many people spend money they haven’t earned, to buy things they don’t want, to impress people they don’t like. - Will Smith",
  "No matter how hard you hug your money, it never hugs back. - H. Jackson Brown, Jr.",
  "Given a ten percent chance of a 100 times payoff, you should take that bet every time. - Jeff Bezos",
  "Just a little bit more. - John D. Rockefeller",
  "If your pattern is to spend everything you get, most likely an increase in cash will just result in an increase in spending. - Robert T. Kiyosaki",
  "If you cannot control your emotions, you cannot control your money. - Warren Buffett",
  "Building wealth has little to do with your income or investment returns, and lots to do with your savings rate. - Morgan Hausel",
  "A bargain is something you can’t use at a price you can’t resist. - Franklin Jones",
  "Inflation is when you pay fifteen dollars for the ten-dollar haircut you used to get for five dollars when you had hair. - Sam Ewing",
  "I have enough money to last me the rest of my life, unless I buy something. - Jackie Mason",
  "I think you will find when your death takes its toll all the money you made will never buy back your soul. - Bob Dylan",
  "Feeling happy now is the fastest way to bring money into your life. - Rhonda Byrne",
  "I guess money can't buy happiness if you shop in the wrong places. - Nora Roberts",
  "A person will be financially secure if additional money is used to purchase income generating assets. - Robert T. Kiyosaki",
  "If you want to know what a man is really like, take notice of how he acts when he loses money. - Simone Weil",
  "I’ve been rich and I’ve been poor. Rich is better. - Sophie Tucker",
  "Every day I get up and look through the Forbes list of the richest people in America. If I’m not there, I go to work. - Robert Orben",
  "If you can count your money, you don’t have a billion dollars. - J. Paul Getty",
  "The man who damns money has obtained it dishonorably; the man who respects it has earned it. - Ayn Rand",
  "If there is anyone to whom I owe money, I’m prepared to forget it if they are. - Errol Flynn",
  "Women need to be less squeamish about making money. - Liz Truss",
  "It’s not hard to spot rich people. They often go out of their way to make themselves known. - Morgan Housel",
  "Expect the best. Prepare for the worst. Capitalize on what comes. - Zig Ziglar",
  "Life started getting good when I started making money. - Balthazar Getty",
  "Wealth is the measure of the cash flow from the asset column compared with the expense column. - Robert T. Kiyosaki",
  "Dishonest money dwindles away, but whoever gathers money little by little makes it grow. - Proverbs 13:11",
  "Money is something you have to make in case you don’t die. - Max Asnas",
  "It’s money. I remember it from when I was single. - Billy Crystal",
  "Always borrow money from a pessimist. He won’t expect it back. - Oscar Wilde",
  "If only God would give me some clear sign! Like making a large deposit in my name at a Swiss bank. - Woody Allen",
  "I’m spending a year dead for tax reasons. - Douglas Adams",
  "All I ask is the chance to prove that money can’t make me happy. - Spike Milligan",
  "A sign of wealth: No longer needing an alarm clock to wake up. - Greg Isenberg",
  "You can be young without money, but you can’t be old without it. - Tennessee Williams",
  "Rich people acquire assets while the poor acquire liabilities which they think are assets. - Robert T. Kiyosaki",
  "Beware of little expenses; a small leak will sink a great ship. - Benjamin Franklin",
  "All sins are forgiven once you start making a lot of money. - Rupaul",
  "Learning how to have money work for you is a lifetime study. - Robert T. Kiyosaki",
  "A simple fact that is hard to learn is that the time to save money is when you have some. - Joe Moore",
  "We can’t see people’s bank accounts or brokerage statements. So we rely on outward appearances to gauge financial success. - Morgan Housel",
  "The question isn’t at what age I want to retire, it’s at what income. - George Foreman",
  "To attract money, focus on wealth. It is impossible to bring more money into your life when you focus on the lack of it. - Rhonda Byrne",
  "One cannot both feast and become rich. - Ashanti Proverb",
  "Money is good for nothing unless you know the value of it by experience. - PT Barnum",
  "The key factor that will determine your financial future is not the economy; the key factor is your philosophy. - Jim Rohn",
  "I don’t pay good wages because I have a lot of money; I have a lot of money because I pay good wages. - Robert Bosch",
  "I had more clothes than I had closets, more cars than garage space, but no money. - Sammy Davis Jr.",
  "Job security meant everything to my educated dad. Learning meant everything to my rich dad. - Robert T. Kiyosaki",
  "Balancing your money is the key to having enough. - Elizabeth Warren",
  "The hardest thing in the world to understand is the income tax. - Albert Einstein",
  "Just because you’re working does not mean you’re making money. That’s two very different things in show business. - Billy Porter",
  "To get rich, you have to be making money while you’re asleep. - David Bailey",
  "Keep your pockets lined. - Greek Proverb",
  "Wealth is largely the result of habit. - John Jacob Astor",
  "Wealth is what you don’t see. - Morgan Housel",
  "People say that money is not the key to happiness, but I figured if you have enough money, you can have a key made. - Joan Rivers",
  "Anything which is physically possible can always be made financially possible; money is a bugaboo of small minds. - Robert A. Heinlein",
  "No man should receive a dollar unless that dollar has been fairly earned. - Theodore Roosevelt",
  "When there are enough assets to generate more than enough income to cover expenses, the balance is reinvested into assets. - Robert T. Kiyosaki",
  "If saving money is wrong, I don’t want to be right! - William Shatner",
  "Money grows on the tree of persistence. - Japanese Proverb",
  "Money is usually attracted, not pursued. - Jim Rohn",
  "If you don’t find a way to make money while you sleep, you will work until you die. - Warren Buffett",
  "Debt is like any other trap, easy enough to get into, but hard enough to get out of. - Josh Billings",
  "It is better to have a permanent income than to be fascinating. - Oscar Wilde",
  "If you work for money, you give the power to your employer. If money works for you, you keep the power and control it. - Robert T. Kiyosaki",
  "Money’s greatest intrinsic value… is its ability to give you control over your time. - Morgan Housel",
  "The habit of saving is itself an education; it fosters every virtue, teaches self-denial, cultivates the sense of order, trains to forethought. - T. T. Munger",
  "Rich people have small TVs and big libraries, and poor people have small libraries and big TVs. - Zig Ziglar",
  "Financial freedom is available to those who learn about it and work for it. - Robert Kiyosaki",
  "The more you need specific elements of a plan to be true, the more fragile your financial life becomes. - Morgan Housel",
  "The greatest gift you can give to yourself is financial independence. - Suze Orman",
  "Is the rich world aware of how four billion of the six billion live? If we were aware, we would want to help out, we’d want to get involved. - Bill Gates",
  "Money cannot buy health, but I'd settle for a diamond-studded Wheelchair. - Dorothy Parker",
  "Life is a game. Money is how we keep score. - Ted Turner",
  "Financial freedom is our birthright, rather than the ‘slave walk’ of the Monday through Friday grind. - Suze Orman",
  "Money is something you trade your life energy for. - Vicki Robin",
  "Count the dollars, not the pennies. - Elizabeth Warren",
  "When your assets generate enough income to cover your expenses, you are wealthy, even if you are not yet rich. - Robert T. Kiyosaki",
  "The safest way to double your money is to fold it over and put it in your pocket. - Kin Hubbard",
  "Money may not buy happiness, but I’d rather cry in a Jaguar than on a bus. - Françoise Sagan",
  "If you have held thoughts in the past that the only way money can come to you is through your job, then let that go immediately. - Rhonda Byrne",
  "Money is better than poverty, if only for financial reasons. - Woody Allen",
  "The hardest financial skill is getting the goalpost to stop moving. - Morgan Housel",
  "Lottery: A tax on people who are bad at math. - Ambrose Bierce",
  "Have a well-thought financial plan that is not dependent upon correctly guessing what will happen in the future. - Barry Ritholtz",
  "The spiritual substance from which comes all visible wealth is never depleted. - Charles Fillmore",
  "A budget is more than just a series of numbers on a page. It is an embodiment of our values. - Barack Obama",
  "Making money is a hobby that will complement any other hobbies you have, beautifully. - Scott Alexander",
  "Financial struggle is often the result of people working all their lives for someone else. - Robert T. Kiyosaki",
  "We insist that money is the root of all evil, and behave as if it were the source of all good. - Charles Edward Jerningham",
  "When a fellow says it ain’t the money but the principle of the thing, it’s the money. - Artemus Ward",
  "The rich invest their money and spend what is left; the poor spend their money and invest what is left. - Jim Rohn",
  "There is a gigantic difference between earning a great deal of money and being rich. - Marlene Dietrich",
  "Don’t think money does everything, or you are going to do everything for money. - Voltaire",
  "Doing well with money has a little to do with how smart you are and a lot to do with how you behave. - Morgan Housel",
  "Wealth is not about having a lot of money; it’s about having a lot of options. - Chris Rock",
  "Making money is easy. It is. The difficult thing in life is not making it; it’s keeping it. - John McAfee",
  "A penny saved is a penny earned. - Benjamin Franklin",
  "Budgeting your money is the key to having enough. - Elizabeth Warren",
  "Manage your spending by creating and sticking to a budget. - Alexa Von Tobel",
  "The gratification of wealth is not found in mere possession or in lavish expenditure, but in its wise application. - Miguel de Cervantes",
  "The rich focus on their asset columns while everyone else focuses on their income statements. - Robert T. Kiyosaki",
  "You have to go broke three times to learn how to make a living. - Casey Stengel",
  "If you want to get rich, remember that the way to do it is via equity, not salary. - Sam Altman",
  "Both poverty and riches are the offspring of thought. - Napoleon Hill",
  "The four most dangerous words in investing are, it’s different this time. - Sir John Templeton",
  "You’ve got to tell your money what to do or it will leave. - Dave Ramsey",
  "Invest for the long haul. Don’t get too greedy and don’t get too scared. - Shelby M C Davis",
  "It’s not about how much money you make. It’s about how much money you keep and how long it works for you. - Robert Kiyosaki",
  "A big part of financial freedom is having your heart and mind free from worry about the what-ifs of life. - Suze Orman",
  "Financial success is not a hard science. It’s a soft skill, where how you behave is more important than what you know. - Morgan Housel",
  "I prefer to be sitting on the beach, but I can’t. I want to be a billionaire. - James Packer",
  "Money will come when you are doing the right thing. - Mike Phillips",
  "Money is like manure. You have to spread it around or it smells. - J. Paul Getty",
  "Wealth is a person’s ability to survive so many numbers of days forward- or, if I stopped working today, how long would I survive? - Robert T. Kiyosaki",
  "Money can’t buy happiness, but it can make you awfully comfortable while you’re being miserable. - Clare Boothe Luce",
  "All the money in the world doesn’t mean a thing if you don’t have time to enjoy it. - Oprah Winfrey",
  "Wealth is like sea-water; the more we drink, the thirstier we become; and the same is true of fame. - Arthur Schopenhauer",
  "With money, the dog dances. - Mexican Proverb",
  "Buy what you don’t need, and soon you’ll sell what you need. - Benjamin Franklin",
  "The best way to look stylish on a budget is to try second-hand, bargain hunting, and vintage. - Orlando Bloom",
  "By desiring little, a poor man makes himself rich. - Democritus",
  "There are people who have money and people who are rich. - Coco Chanel",
  "There's nothing in the world so demoralizing as money. - Sophocles",
  "Buy when everyone else is selling and hold until every else is buying. That’s not just a catchy slogan. It’s the very essence of successful investing. - J Paul Getty",
  "The more you learn, the more you earn. - Warren Buffett",
  "Rich people believe “I create my life”. Poor people believe “Life happens to me”. - T. Harv Eker",
  "When somebody says it’s not about the money, it’s about the money. - H.L. Mencken",
  "For I don't care too much for money, for money can't buy me love. - The Beatles",
  "Don’t wait to buy real estate. Buy real estate and wait. - Will Rogers",
  "Within certain limits, it is actually true that the less money you have, the less you worry. - George Orwell",
  "Keep your daytime job, but start buying real assets, not liabilities. - Robert T. Kiyosaki",
  "Many folks think they aren’t good at earning money, when what they don’t know is how to use it. - Frank A. Clark",
  "The quickest way to double your money is to fold it in half and put it in your back pocket. - Will Rogers",
  "Earn with your mind, not your time. - Naval Ravikant",
  "If you make meaning, you’ll make money. - Guy Kawasaki",
  "Every negative thought, feeling, or emotion is blocking your good from coming to you, and that includes money. - Rhonda Byrne",
  "I make myself rich by making my wants few. - Henry David Thoreau",
  "The money you have gives you freedom; the money you pursue enslaves you. - Jean-Jacques Rousseau",
  "There are a great many people accumulating what they think is vast wealth, but it’s only money. - Alan Watts",
  "Money is like a sixth sense—and you can’t make use of the other five without it. - William Somerset Maugham",
  "Financial peace isn’t the acquisition of stuff. It’s learning to live on less than you make. - Dave Ramsey",
  "Spend your money on the things money can buy. Spend your time on the things money can’t buy. - Haruki Murakami",
  "The art of living easily as to money is to pitch your scale of living one degree below your means. - Sir Henry Taylor",
  "With money comes great power that requires the right knowledge to keep it and make it multiply. - Robert T. Kiyosaki",
  "Money won’t create success, the freedom to make it will. - Nelson Mandela",
  "Money doesn’t grow on trees, but grows on intelligent minds. - Matshona Dhliwayo",
  "When I had money everyone called me brother. - Polish Proverb",
  "In investing, what is comfortable is rarely profitable. - Robert Arnott",
  "Money moves from those who do not manage it to those who do. - Dave Ramsey",
  "There is only one class in the community that thinks more about money than the rich, and that is the poor. - Oscar Wilde",
  "Making money is art and working is art and good business is the best art. - Andy Warhol",
  "Get the money honestly if you can. - American Proverb",
  "For the sake of life on Earth, we must put a limit on wealth. - George Monbiot",
  "If you want to get rich, think of saving as earning. - Andrew Carnegie",
  "Money can only give happiness where there is nothing else to give it. - Jane Austen",
  "Simple math and common sense are all you need to do well financially. - Robert T. Kiyosaki",
  "When I was young, I thought money was the most important thing in life. Now that I am old , I know that it is. - Oscar Wilde",
  "Whoever said 'money can't buy happiness' really knew what they were talking about. - Elon Musk",
  "Getting money is like digging with a needle, spending it like water soaking into the sand. - Japanese Proverb",
  "The more of it [money] one has, the more one wants. - Benjamin Franklin",
  "There is a difference between being poor and being broke. Broke is temporary. Poor is eternal. - Robert T. Kiyosaki",
  "Spending money to show people how much money you have is the fastest way to have less money. - Morgan Housel",
  "Money frees you from doing things you dislike. Since I dislike doing nearly everything, money is handy. - Groucho Marx",
  "No wealth can ever make a bad man at peace with himself. - Plato",
  "Focus on not enough money, and you will create untold more circumstances of not having enough money. - Rhonda Byrne",
  "No one has ever become poor by giving. - Anne Frank",
  "What’s the use of happiness? It can’t buy you money. - Henry Youngman",
  "Of all the icy blasts that blow on love, a request for money is the most chilling. - Gustave Flaubert",
  "The chief value of money lies in the fact that one lives in a world in which it is overestimated. - H. L. Mencken",
  "Being rich is having money; being wealthy is having time. - Margaret Bonanno",
  "If you want abundance, if you want prosperity, then focus on abundance. Focus on prosperity. - Lisa Nichols",
  "Increased spending throws families into greater debt and into more financial uncertainty. - Robert Kiyosaki",
  "Before you invest, investigate. - William A Ward",
  "When it comes to creating wealth, wealth is a mindset. It's all about how you think. - David Schirmer",
  "Most people have a goal of getting out of debt. That will keep you in debt forever. - Bob Proctor",
  "Modern capitalism is a pro at two things: generating wealth and generating envy. - Morgan Housel",
  "People become a slave to money – and then get angry at their boss. - Robert Kiyosaki",
  "It’s simple arithmetic: 'Your income can grow only to the extent you do'. - T. Harv Eker",
  "Lazy hands make for poverty, but diligent hands bring wealth. - Proverbs 10:4",
  "Money is the best deodorant. - Elizabeth Taylor",
  "Money makes your life easier. If you're lucky to have it, you're lucky. - Robert De Niro",
  "Money can't buy you happiness, but it can buy you a yacht big enough to pull up right alongside it. - David Lee Roth",
  "Money, if it does not bring you happiness, will at least help you be miserable in comfort. - Helen Gurley Brown",
  "It is a kind of spiritual snobbery that makes people think they can be happy without money. - Albert Camus",
  "An investment in knowledge pays the best interest. - Benjamin Franklin",
  "So you think that money is the root of all evil. Have you ever asked what is the root of all money? - Ayn Rand",
  "The investor’s chief problem — and even his worst enemy — is likely to be himself. - Benjamin Graham",
  "Someday I want to be rich. Some people get so rich they lose all respect for humanity. That's how rich I want to be. - Rita Rudner",
  "Make money your god and it will plague you like the devil. - Henry Fielding",
  "Don't tell me where your priorities are. Show me where you spend your money and I'll tell you what they are. - James W. Frick",
  "To acquire money requires valor, to keep money requires prudence, and to spend money well is an art. - Berthold Auerbach",
  "Before you spend, earn. - William A Ward",
  "While money can’t buy happiness, it certainly lets you choose your own form of misery. - Groucho Marx",
  "Even the judgment of hell depends on money. - Japanese Proverb",
  "If you want to make a million you don't have to understand money, what you have to understand is people's fears about money. - William Gaddis",
  "Unfortunately most ways of making big money take a long time. By the time one has made the money one is too old to enjoy it. - Ian Fleming",
  "Knowledge may be power, but money buys both. - V.E. Schwab",
  "Money-makers are tiresome company, as they have no standard but cash value. - Plato",
  "Money can't buy happiness, but it certainly is a stress reliever. - Besa Kosova",
  "There are three faithful friends, an old wife, an old dog, and ready money. - Benjamin Franklin",
  "Its easier to feel a little more spiritual with a couple of bucks in your pocket. - Craig Ferguson",
  "Money is like gasoline during a road trip. You don’t want to run out of gas on your trip, but you’re not doing a tour of gas stations. - Tim O'Reilly",
  "It all came down to money - the great equalizer and common denominator. - James Ellroy"
];